### ISSUE TITLE
Thanks for Sharing

### ISSUE THREAD

**Issue by idkjs** [jtaylor1989/Zopher#1]
I cant get this to go. The app seems to break after adding native-base with this error:
```s
[18:06:56] Unable to resolve "@expo/vector-icons/FontAwesome5" from "node_modules/native-base/dist/src/basic/IconNB.js"
```
Not related to aws but figured you could point me in the right direction on debugging this kind of thing. I have been in the issues and SO but have not found a solution that works.

The error above is from downloading and running this repo. Any guidance would be greatly appreciated. Thank you.

**Comment by youneshenniwrites** [comment]
Thanks for reaching out.
Can you please show your package.json config ?
What machine are you running the app in ? and which simulator (iOS or Android).

Check this [link](https://github.com/oblador/react-native-vector-icons/issues/402) if this might help:

**Comment by idkjs** [comment]
Env is:

ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G3025
yarn version: 1.12.3
node version: v10.8.0

I read through that link before reaching out. No luck there. package.json is same as this repo. I downloaded this and added adding aws-exports.js, then ran.

**Comment by youneshenniwrites** [comment]
You obviously have the same config as me.
I tried to download the repo and install native-base and indeed I have the same problem as you. 

I solved this by running:
   `yarn remove native-base`

and forcing the install of version 2.8.2 (used in the repo)

   `yarn add native-base@2.8.2`

I am aware this is not a permanent solution but this should set you up and running.

**Comment by gabriel-TheCode** [comment]
Thanks, You saved my day.
